# Generated by Django 5.2 on 2025-05-04 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('details', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='client_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('not_started', 'NOT_STARTED'), ('in_progress', 'IN_PROGRESS'), ('completed', 'COMPLETED'), ('on_hold', 'ON_HOLD')], db_index=True, default='not_started', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.client')),
            ],
        ),
    ]
