# Generated by Django 5.2 on 2025-06-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('users', '0002_userex_username'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='project_status_idx',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='status',
            new_name='project_status',
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_status'], name='project_status_idx'),
        ),
    ]
