# Generated by Django 5.2 on 2025-05-04 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('domain', 'DOMAIN'), ('hosting', 'HOSTING'), ('server', 'SERVER')], db_index=True, max_length=20)),
                ('details', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(db_index=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='projects.project')),
            ],
            options={
                'indexes': [models.Index(fields=['type'], name='service_type_idx'), models.Index(fields=['end_date'], name='service_end_date_idx')],
            },
        ),
    ]
