# Generated by Django 5.2 on 2025-05-04 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('project_progress', 'Project Progress'), ('team_performance', 'Team Performance'), ('deadline_risk', 'Deadline Risk')], max_length=20)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('generated_by', models.ForeignKey(limit_choices_to={'role__in': ['admin', 'manager', 'employee']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userex')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'indexes': [models.Index(fields=['report_type'], name='report_type_idx'), models.Index(fields=['created_at'], name='report_created_at_idx')],
            },
        ),
    ]
