# Generated by Django 5.2 on 2025-06-01 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='reports_rep_report__dbb097_idx',
            old_name='report_type_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='reports_rep_created_a6aabf_idx',
            old_name='report_created_at_idx',
        ),
        migrations.AddField(
            model_name='report',
            name='filters',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='report',
            name='is_cached',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='generated_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['admin', 'manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['is_cached'], name='reports_rep_is_cach_2b8b2d_idx'),
        ),
    ]
