# Generated by Django 5.2 on 2025-06-22 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_options_and_more'),
        ('users', '0002_userex_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='generated_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['admin', 'manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userex'),
        ),
    ]
