# Generated by Django 5.2 on 2025-05-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('not_started', 'NOT_STARTED'), ('in_progress', 'IN_PROGRESS'), ('completed', 'COMPLETED')], db_index=True, default='not_started', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('deadline', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
    ]
