# Generated by Django 5.2 on 2025-05-10 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('tasks', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('deadline', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('planning', 'PLANNING'), ('in_progress', 'IN_PROGRESS'), ('completed', 'COMPLETED'), ('delayed', 'DELAYED')], db_index=True, default='planning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_deadline_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_project_idx',
        ),
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project'),
        ),
        migrations.AddField(
            model_name='task',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.milestone'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'deadline'], name='task_status_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['status'], name='milestone_status_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['deadline'], name='milestone_deadline_idx'),
        ),
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_project_milestone'),
        ),
    ]
