# Generated by Django 5.2 on 2025-06-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_project_status_idx_and_more'),
        ('tasks', '0003_milestone_remove_task_task_status_idx_and_more'),
        ('users', '0002_userex_username'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='milestone',
            name='milestone_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_status_deadline_idx',
        ),
        migrations.RenameField(
            model_name='milestone',
            old_name='status',
            new_name='milestone_status',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='task_status',
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['milestone_status'], name='milestone_status_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_status', 'deadline'], name='task_status_deadline_idx'),
        ),
    ]
